class_name EventBusService
extends Node

@warning_ignore("unused_signal")
signal map_change_requested(map_id: StringName, spawn_id: StringName)
@warning_ignore("unused_signal")
signal map_will_change(from_id: StringName, to_id: StringName)
@warning_ignore("unused_signal")
signal map_changed(map_id: StringName)
@warning_ignore("unused_signal")
signal map_change_failed(map_id: StringName, error: Error)
@warning_ignore("unused_signal")
signal time_advanced(unit: int, before: Dictionary, delta: int)
@warning_ignore("unused_signal")
signal day_advanced(previous_day: int, current_day: int)
@warning_ignore("unused_signal")
signal inventory_changed(owner_id: StringName)
@warning_ignore("unused_signal")
signal container_changed(container_id: StringName)
@warning_ignore("unused_signal")
signal bar_selection_changed(source: int, selected_index: int)
@warning_ignore("unused_signal")
signal active_hand_changed(source: int, item_id: StringName, amount: int)
@warning_ignore("unused_signal")
signal player_state_changed(state: PlayerState)
@warning_ignore("unused_signal")
signal interaction_committed(action_id: StringName, cells: Array[Vector2i])
@warning_ignore("unused_signal")
signal cells_tool_used(tool_kind: ToolMeta.ToolKind, cells: Array[Vector2i], stamina_spent: int)
@warning_ignore("unused_signal")
signal cell_projection_failed(cells: Array[Vector2i], error: Error)
@warning_ignore("unused_signal")
signal request_tool_feedback(event_id: StringName, cells: Array[Vector2i])
@warning_ignore("unused_signal")
signal save_completed(slot: int)
@warning_ignore("unused_signal")
signal load_completed(slot: int)
