class_name EventBusService
extends Node

@warning_ignore("unused_signal")
signal map_change_requested(map_id: StringName, spawn_id: StringName)
@warning_ignore("unused_signal")
signal map_changed(map_id: StringName)
@warning_ignore("unused_signal")
signal player_interior_changed(interior: bool)
@warning_ignore("unused_signal")
signal house_interior_changed(house: Node2D, actor: Node2D, interior: bool)
@warning_ignore("unused_signal")
signal map_change_failed(map_id: StringName, error: Error)
@warning_ignore("unused_signal")
signal time_advanced
@warning_ignore("unused_signal")
signal day_advanced
@warning_ignore("unused_signal")
signal weather_changed(weather_id: StringName, previous_weather_id: StringName)
@warning_ignore("unused_signal")
signal inventory_changed(owner_id: StringName)
@warning_ignore("unused_signal")
signal container_changed(container_id: StringName)
@warning_ignore("unused_signal")
signal bar_selection_changed(source: int, selected_index: int)
@warning_ignore("unused_signal")
signal active_hand_changed(source: int, item_id: StringName, amount: int)
@warning_ignore("unused_signal")
signal player_state_changed(state: PlayerState)
@warning_ignore("unused_signal")
signal npc_states_changed()
@warning_ignore("unused_signal")
signal cell_projection_failed(cells: Array[Vector2i], error: Error)
@warning_ignore("unused_signal")
@warning_ignore("unused_signal")
signal request_invalid_feedback(reason: StringName)
@warning_ignore("unused_signal")
signal dialogue_started(dialogue_id: StringName)
@warning_ignore("unused_signal")
signal dialogue_ended()
@warning_ignore("unused_signal")
signal save_completed(slot: int)
@warning_ignore("unused_signal")
signal load_completed(slot: int)
